version: 2
references:
  working_server_directory: &working_server_directory ~/coding-challenge-fullstack
  working_frontend_directory: &working_frontend_directory ~/coding-challenge-fullstack

jobs:
  build_server:
  run:
    name: Build server image
    command: |
      docker build -f Dockerfile.server

  deploy_server:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Server to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2
  build-deploy:
    jobs:
      - build_server
      - deploy_server:
          requires:
            - build_server
          filters:
            branches:
              only: disable
